### ISSUE TITLE
mail-downloader throwing multiple errror messages and not downloading any files

### ISSUE THREAD

**Issue by jensstruemper** [loeffel-io/mail-attachment-downloader#1]
Hi! 
mail-downloader throwing several error messages which seem to be caused by a few individual email. However, there're no files being stored to hard disk at all.

➜ ./mail-downloader -config=config.yml -from="2019-01-01" -to="2019-12-31"
Fetching messages...
1609 / 1609 [-------------------------------------------------------------------------------------------------------------------->] 100.00% 22 p/sProcessing messages...
630 / 1609 [---------------------------------------------->________________________________________________________________________] 39.15% 16 p/s2021/04/09 15:06:46 Loading pages (1/6)
Error: Failed to load cid:15597356275cf7ad4b4cebd621105974@auer-packaging.de, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15597356275cf7ad4b4cf9e149013982@auer-packaging.de, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15597356275cf7ad4b4d062769744683@auer-packaging.de, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15597356275cf7ad4b4d126685642393@auer-packaging.de, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15597356275cf7ad4b4d1ec639230779@auer-packaging.de, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError

647 / 1609 [----------------------------------------------->_______________________________________________________________________] 40.21% 16 p/s2021/04/09 15:06:48 Loading pages (1/6)
Error: Failed to load cid:15598350775cf931c596b9e725385405@auer-packaging.com, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15598350775cf931c596bd3876396194@auer-packaging.com, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15598350775cf931c596bf9460798641@auer-packaging.com, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15598350775cf931c596c1d798517856@auer-packaging.com, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Error: Failed to load cid:15598350775cf931c596c3f081866304@auer-packaging.com, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError

1176 / 1609 [-------------------------------------------------------------------------------------->________________________________] 73.09% 7 p/s2021/04/09 15:07:34 Loading pages (1/6)
Error: Failed to load cid:signatur, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError

1534 / 1609 [-------------------------------------------------------------------------------------------------------------------------------------------------------------------->________] 95.34% 15 p/s2021/04/09 15:08:08 Loading pages (1/6)
Error: Failed to load cid:image001.png@01D5B27C.CAC2F1C0, with network status code 301 and http status code 0 - Protocol "cid" is unknown
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Exit with code 1 due to network error: ProtocolUnknownError

1581 / 1609 [------------------------------------------------------------------------------------------------------------------------------------------------------------------------->___] 98.26% 18 p/sDone

################

COFNIG.yml

imap:
  username: xxx
  password: xxx
  server: imap.gmail.com
  port: 993

attachments:
  mimetypes:
    - application/pdf

mails:
  subjects: # subject contains
    - invoice, amazon # invoice AND amazon
    - rechnung # OR rechnung
    - receipt # OR receipt
    - invoice

**Comment by stefanwuthrich** [comment]
I get to the same error, but googling some seconds brings me to :
https://stackoverflow.com/questions/55317467/converting-gmail-to-pdf-embedded-images-in-html
Seams to be wkhtmltopdf related.

**Comment by loeffel-io** [comment]
yeah this is wkhtmltopdf related and belongs to the email itself - but this should not stop downloading the working pdfs

**Comment by jensstruemper** [comment]
Just tested it again and I can confirm it is working now.
